=== DanielGZamora/LenguajeMarcas/XML/examenxslt/formulario.dtd
<!ELEMENT formulario (conjunto*)>
<!ELEMENT conjunto (leyenda, campo*)>
<!ELEMENT leyenda (#PCDATA)>
<!ELEMENT campo (etiqueta?,entrada)>
<!ELEMENT etiqueta (#PCDATA)>
<!ELEMENT entrada EMPTY>
<!ATTLIST entrada tipo CDATA #REQUIRED>

=== DanielGZamora/LenguajeMarcas/XML/examenxslt/formulario2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE formulario SYSTEM "formulario.dtd">
<formulario>
    <conjunto>
        <leyenda>Entrada de usuario</leyenda>
        <campo>
            <etiqueta>Username</etiqueta>
            <entrada tipo="text" />
        </campo>
        <campo>
            <etiqueta>Password</etiqueta>
            <entrada tipo="password" />
        </campo>
    </conjunto>
    <conjunto>
        <leyenda>Botones</leyenda>
        <campo>
            <etiqueta>Enviar</etiqueta>
            <entrada tipo="submit" />
        </campo>
        <campo>
            <etiqueta>Limpiar</etiqueta>
            <entrada tipo="reset" />
        </campo>
    </conjunto>
</formulario>

=== DanielGZamora/LenguajeMarcas/XML/examenxslt/formulario1.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="formulario1.xsl" type="text/xsl"?>
<!DOCTYPE formulario SYSTEM "formulario.dtd">

<formulario>
    <conjunto>
        <leyenda>Registro de alumno</leyenda>
        <campo>
            <etiqueta>Username</etiqueta>
            <entrada tipo="text" />
        </campo>
        <campo>
            <etiqueta>Password</etiqueta>
            <entrada tipo="password" />
        </campo>
        <campo>
            <etiqueta>Edad</etiqueta>
            <entrada tipo="number" />
        </campo>
        <campo>
            <etiqueta>CV</etiqueta>
            <entrada tipo="textarea" />
        </campo>
        <campo>
            <etiqueta>Fecha de alta</etiqueta>
            <entrada tipo="date" />
        </campo>
        <campo>
            <etiqueta>Foto</etiqueta>
            <entrada tipo="file" />
        </campo>
        <campo>
            <entrada tipo="radio" />
        </campo>
    </conjunto>
</formulario>
