=== DanielGZamora/LenguajeMarcas/html/examenes/examenxslt/examenxsltPart2/formulario.dtd
<!ELEMENT formulario (conjunto*)>
<!ELEMENT conjunto (leyenda, campo*)>
<!ELEMENT leyenda (#PCDATA)>
<!ELEMENT campo (texto,etiqueta?,entrada)>
<!ELEMENT texto (#PCDATA)>
<!ELEMENT etiqueta (#PCDATA)>
<!ELEMENT entrada EMPTY>
<!ATTLIST entrada tipo CDATA #REQUIRED>
<!ATTLIST entrada nombre CDATA #REQUIRED>

=== DanielGZamora/LenguajeMarcas/html/examenes/examenxslt/examenxsltPart2/formulario2.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="SOLUCION1.xsl" type="text/xsl"?>
<!DOCTYPE formulario SYSTEM "formulario.dtd">
<formulario>
    <conjunto>
        <leyenda>Entrada de usuario</leyenda>
        <campo>
            <texto>text</texto>
            <etiqueta>Username</etiqueta>
            <entrada tipo="text" nombre=""/>
        </campo>
        <campo>
            <texto></texto>
            <etiqueta>Password</etiqueta>
            <entrada tipo="password" nombre=""/>
        </campo>
    </conjunto>
    <conjunto>
        <leyenda>Botones</leyenda>
        <campo>
            <texto></texto>
            <etiqueta>Enviar</etiqueta>
            <entrada tipo="submit" nombre=""/>
        </campo>
        <campo>
            <texto></texto>
            <etiqueta>Limpiar</etiqueta>
            <entrada tipo="reset" nombre=""/>
        </campo>
    </conjunto>
</formulario>

=== DanielGZamora/LenguajeMarcas/XML/examenxsltPart2/formulario1.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="SOLUCION1.xsl" type="text/xsl"?>
<!DOCTYPE formulario SYSTEM "formulario.dtd">

<formulario>
    <conjunto>
        <leyenda>Registro de alumno</leyenda>
        <campo>
            <texto>Text: </texto>
            <etiqueta>Username</etiqueta>
            <entrada tipo="text" nombre=""/>
        </campo>
        <campo>
            <texto>Text: </texto>
            <etiqueta>Password</etiqueta>
            <entrada tipo="password" nombre=""/>
        </campo>
        <campo>
            <texto>Text: </texto>
            <etiqueta>Edad</etiqueta>
            <entrada tipo="number" nombre=""/>
        </campo>
        <campo>
            <texto>Text: </texto>
            <etiqueta>CV</etiqueta>
            <entrada tipo="textarea" nombre=""/>
        </campo>
        <campo>
            <texto>Text: </texto>
            <etiqueta>Fecha de alta</etiqueta>
            <entrada tipo="date" nombre=""/>
        </campo>
        <campo>
            <texto>Text: </texto>
            <etiqueta>Foto</etiqueta>
            <entrada tipo="file" nombre=""/>
        </campo>
        <campo>
            <texto>Text: </texto>
            <entrada tipo="radio" nombre=""/>
        </campo>
    </conjunto>
</formulario>

=== DanielGZamora/LenguajeMarcas/html/examenes/examenxslt/examenxsltPart2/formulario1.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="formulario1.xsl" type="text/xsl"?>
<!DOCTYPE formulario SYSTEM "formulario.dtd">

<formulario>
    <conjunto>
        <leyenda>Registro de alumno</leyenda>
        <campo>
            <texto>Texto:</texto>
            <etiqueta>Username</etiqueta>
            <entrada tipo="text" nombre="username" />
        </campo>
        <campo>
            <texto>Texto:</texto>
            <etiqueta>Password</etiqueta>
            <entrada tipo="password" nombre="password" />
        </campo>
        <campo>
            <texto>Texto:</texto>
            <etiqueta>Edad</etiqueta>
            <entrada tipo="number" nombre="edad" />
        </campo>
        <campo>
            <texto>Texto:</texto>
            <etiqueta>CV</etiqueta>
            <entrada tipo="textarea" nombre="cv" />
        </campo>
        <campo>
            <texto>Texto:</texto>
            <etiqueta>Fecha de alta</etiqueta>
            <entrada tipo="date" nombre="fechaAlta" />
        </campo>
        <campo>
            <texto>Texto:</texto>
            <etiqueta>Foto</etiqueta>
            <entrada tipo="file" nombre="foto" />
        </campo>
        <campo>
            <texto>Texto:</texto>
            <etiqueta>Radio</etiqueta>
            <entrada tipo="radio" nombre="radio" />
        </campo>
    </conjunto>
</formulario>
